export const START_GAME = 'START_GAME';
export const MOVE_CHARACTER_LEFT = 'MOVE_CHARACTER_LEFT';
export const MOVE_CHARACTER_RIGHT = 'MOVE_CHARACTER_RIGHT';
export const MOVE_CHARACTER_UP = 'MOVE_CHARACTER_UP';
export const MOVE_CHARACTER_DOWN = 'MOVE_CHARACTER_DOWN';